THEME_2021_4Q = [
    "mRNA",
    "GeneTherapy",
    "Telemedicine",
    "AI Diagnostics",
    "Solar Energy",
    "Wind Energy",
    "Hydrogen Energy",
    "ESG (Environment, Social, Governance)",
    "Cloud Computing",
    "AI (Artificial intelligence)",
    "Metaverse",
    "Cybersecurity",
    "Data Centers",
    "Satellite",
    "Space Tourism",
    "Reusable Rockets",
    "Cryptocurrency",
    "NFT(Non-fungible token)",
    "Supply Chain",
    "Infrastructure",
]

THEME_2022_1Q = [
    'Green Energy',
    'Food Commodities',
    'Space Exploration',
    'Cryptocurrency Volatility',
    'Electric Vehicles',
    'Nuclear Fusion',
    'Artificial Intelligence',
    'Defense Technology',
    'Telecommunications', 
    'Oil and Gas', 
    'Banking Sector', 
    'Pharmaceuticals',
    'Renewable Energy',
    'Gold Market', 
    'Tourism', 
    'Agriculture',
    'Aerospace',
    'Biotechnology',
    'Telecom Infrastructure',
    'Climate Technology'
]

THEME_2022_2Q = [
    'Space Tourism', 
    'Electric Vehicles', 
    'Cryptocurrency Adoption', 
    'Nuclear Energy', 
    'Private Spaceflight', 
    'Fusion Energy', 
    'Climate Change Mitigation',
    'Cybersecurity',
    'Renewable Energy', 
    'Telecommunications',
    'Biotechnology',
    'Artificial Intelligence',
    'Space Exploration', 
    'Digital Currency', 
    'E-commerce', 
    'Pharmaceuticals',
    'Agriculture Technology',
    'Defense Technology', 
    'Food Security', 
    'Healthcare Innovation'
]

THEME_2022_3Q = [
    "Renewable Energy",
    "Defense Technology",
    "Cybersecurity",
    "Biotechnology",
    "Space Economy",
    "Electric Vehicles",
    "Hydrogen Energy",
    "Agritech",
    "Climate Resilience",
    "Green Infrastructure",
    "Robotics",
    "Artificial Intelligence",
    "Fintech",
    "E-commerce",
    "Cloud Computing",
    "Quantum Computing",
    "Sustainable Investing",
    "Water Technology",
    "Tourism",
    "Supply Chain Resilience"
]

THEME_2022_4Q = [
    "Emerging Markets",         
    "Retail Trading",           
    "Space Exploration",        
    "Commercial Spaceflight",   
    "Cryptocurrency",           
    "China Innovation",         
    "Media & Entertainment",    
    "Digital Assets",           
    "Electric Vehicles",        
    "Clean Energy",             
    "Climate Tech",             
    "Vaccines & Biotech",       
    "Space Tourism",            
    "Crypto Regulation",        
    "Renewable Power",          
    "Telemedicine",             
    "Cybersecurity",            
    "5G Networks",              
    "E-commerce",               
    "Artificial Intelligence",
]

THEME_2023_1Q = [
    'Renewable Energy', 'Electric Vehicles', 'Cryptocurrency Volatility', 'Space Exploration', 'Nuclear Fusion', 'Artificial Intelligence', 'Social Media Acquisition', 'Banking Sector Instability', 'Gold Market', 'Oil Price Cap', 'Telecommunications', 'Defense Sector', 'Food Security', 'Biotechnology', 'Tourism Recovery', 'Semiconductors', 'Natural Disasters', 'Healthcare Innovation', 'Infrastructure Development', 'Climate Change Mitigation']

THEME_2023_2Q = [
    'Electric Vehicles', 
    'Cryptocurrency Volatility', 
    'Nuclear Fusion',
    'Space Exploration', 
    'AI Technology', 
    'Interest Rate Hikes', 
    'Grain Exports', 
    'Oil Price Cap', 
    'Bank Failures', 
    'Climate Change Mitigation', 
    'Marine Conservation', 
    'Synthetic Biology', 
    'Military Technology',
    'Telecommunications', 
    'Natural Disasters', 
    'Bank Mergers', 
    'Renewable Energy',
    'Defense Sector', 
    'Food Security',
    'Digital Currency'
    ]

THEME_2023_3Q = [
    "Global Energy",
    "Social Media",
    "Blockchain Regulation",
    "Space Exploration",
    "AI & Generative Language Models",
    "Next-Gen Nuclear Energy",
    "European Monetary Integration",
    "Frontier Markets Risk",
    "EV Transition",
    "Regional Banks",
    "European Banking Consolidation",
    "U.S. Mid-Sized Banks",
    "Luxury Goods Consolidation",
    "De-Dollarization",
    "Geopolitical Influence",
    "Media & Entertainment Disruption",
    "Consumer Discretionary",
    "Sovereign ESG Risk",
    "Indian Innovation",
    "Eurozone Interest Rate Sensitivity"
]